name: flutter_flexible_data_table
description: "A package for build flutter data table."
version: 0.0.1
homepage: 'https://github.com/AAAAAApril/flutter_flexible_data_table'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
